/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AluguerRouteImport } from './routes/aluguer'
import { Route as IndexRouteImport } from './routes/index'

const AluguerRoute = AluguerRouteImport.update({
  id: '/aluguer',
  path: '/aluguer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluguer': typeof AluguerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aluguer': typeof AluguerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aluguer': typeof AluguerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aluguer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aluguer'
  id: '__root__' | '/' | '/aluguer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AluguerRoute: typeof AluguerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/aluguer': {
      id: '/aluguer'
      path: '/aluguer'
      fullPath: '/aluguer'
      preLoaderRoute: typeof AluguerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AluguerRoute: AluguerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
