/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AluguerDeBicicletasRouteImport } from './routes/aluguer-de-bicicletas'
import { Route as IndexRouteImport } from './routes/index'

const AluguerDeBicicletasRoute = AluguerDeBicicletasRouteImport.update({
  id: '/aluguer-de-bicicletas',
  path: '/aluguer-de-bicicletas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluguer-de-bicicletas': typeof AluguerDeBicicletasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aluguer-de-bicicletas': typeof AluguerDeBicicletasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aluguer-de-bicicletas': typeof AluguerDeBicicletasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aluguer-de-bicicletas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aluguer-de-bicicletas'
  id: '__root__' | '/' | '/aluguer-de-bicicletas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AluguerDeBicicletasRoute: typeof AluguerDeBicicletasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/aluguer-de-bicicletas': {
      id: '/aluguer-de-bicicletas'
      path: '/aluguer-de-bicicletas'
      fullPath: '/aluguer-de-bicicletas'
      preLoaderRoute: typeof AluguerDeBicicletasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AluguerDeBicicletasRoute: AluguerDeBicicletasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
